# Generated by Django 5.0 on 2023-12-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='item_quatity',
        ),
        migrations.AddField(
            model_name='product_details',
            name='item_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='item_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='item_quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
