# Generated by Django 5.0 on 2023-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_product_details_item_quatity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
