# Generated by Django 5.0 on 2024-01-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
